name: Create GitHub release
description: Mostly replicate actions/create-release (which is now unmaintained)
# NOTE: Needs GITHUB_TOKEN env variable

inputs:
  tag_name:
    description: 'The name of the tag.'
    required: true
  release_name:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: true
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  body_path:
    description: 'Path to file with information about the tag.'
    required: false
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one.'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release.'
    required: false
    default: false
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
    required: false
  repo:
    description: 'Repository on which to release. Used only if you want to create the release on another repo'
    required: false

outputs:
  html_url:
    description: 'The URL users can navigate to in order to view the release'
    value: ${{ steps.main.outputs.html_url }}

runs:
  using: composite
  steps:
    - shell: bash
      id: main
      env:
        TAG: ${{ inputs.tag_name }}
        REPO: ${{ inputs.repo || github.repository }}
        TARGET: ${{ inputs.commitish || github.sha }}
        TITLE: ${{ inputs.release_name }}
        BODY: ${{ inputs.body }}
        BODY_PATH: ${{ inputs.body_path }}
        IS_DRAFT: ${{ inputs.draft }}
        IS_PRERELEASE: ${{ inputs.prerelease }}
      run: |
        node ${{ github.action_path }}/create-release.js
