name: Checkout copyright-update branch
description: Creates a branch called "copyright-<year>"

# env outputs:
  # YEAR: The current year
  # BRANCH_NAME: The copyright-update branch name

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        year=$(date '+%Y' --utc)
        branch_name="copyright-${year}"
        git checkout -b "$branch_name"

        echo "YEAR=$year" >> $GITHUB_ENV
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
