name: Configure git
description: Set the bot as author

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config push.default current || true  # won't work if cwd is not git repo
