name: Upload coverage to Codecov
description: Fault tolerant unlike codecov/codecov-action

inputs:
  name:
    description: Custom defined name for the upload
    required: false
  flags:
    description: Flag the upload to group coverage metrics (unittests, uitests, etc.). Multiple flags are separated by a comma (ui,chrome)
    required: false
  fail_ci_if_error:
    description: Specify if CI pipeline should fail when Codecov runs into errors during upload. Defaults to false
    required: false

runs:
  using: composite
  steps:
    - id: upload
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        name: ${{ inputs.name }}
        flags: ${{ inputs.flags }}
        fail_ci_if_error: true

    - if: failure() && steps.upload.outcome == 'failure'
      shell: bash
      env:
        DELAY: '20'
      run: |
        echo "::error::Failed to upload, retrying in ${DELAY}s ..."
        sleep "$DELAY"

    - if: failure() && steps.upload.outcome == 'failure'
      uses : codecov/codecov-action@v3
      with:
        name: ${{ inputs.name }}
        flags: ${{ inputs.flags }}
        fail_ci_if_error: ${{ inputs.fail_ci_if_error }}
