name: Create & checkout PR branch
description: Creates branch named "prepare-<version>". Also sets GitHub Actions bot as author.
inputs:
  prefix:
    description: Set this to override the default branch name prefix "prepare-"
    required: false
    default: 'prepare-'
  version:
    description: Version number of the release. If this is not set, will use the env var VERSION instead.
    required: false
# env outputs:
  # HEAD_REF: The PR branch name
runs:
  using: composite
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git config push.default current

    - name: Create & checkout PR branch
      shell: bash
      env:
        BRANCH_PREFIX: ${{ inputs.prefix }}
      run: |
        if [[ "$INPUT_VERSION" ]]; then
          VERSION=$INPUT_VERSION
        fi
        if [[ -z "$VERSION" ]]; then
          echo "::error:: No version number supplied"
          exit 1
        fi

        HEAD_REF="${BRANCH_PREFIX}${VERSION}"
        git checkout -b "$HEAD_REF"

        echo "::set-env name=HEAD_REF::$HEAD_REF"
