name: Build Python package
description: Build Python package wheel distribution. Must be run in the (usually top-level) package dir containing setup.py
inputs:
  check-dependencies:
    description: Try pip-installing dependencies to make sure we are pinned to released versions on PyPI
    required: false
    default: true
  dry-run:
    description: Obsolete; there is no longer a difference between dry-run and real build
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        if [[ -f setup.py ]]; then
          # old style setup.py project
          # (must manually install build dependencies)
          echo "setup.py detected"
          python3 -m pip install wheel
          python3 setup.py bdist_wheel sdist
        else
          # PEP517 project
          # (must install a builder, this installs build deps for us)
          echo "PEP 517 project detected"
          python3 -m pip install build
          python3 -m build
        fi

    - name: Check build
      shell: bash
      run: |
        python3 -m pip install twine
        twine check dist/*

    - name: Check dependencies
      if: inputs.check-dependencies == 'true'
      # ^ string comparison needed due to https://github.com/actions/runner/issues/2238
      shell: bash
      run: python3 -m pip install -e .[all] --dry-run --ignore-installed
