name: Build Python package
description: Build Python package wheel distribution. Must be run in the (usually top-level) package dir containing setup.py
inputs:
  dry-run:
    description: Obsolete; there is no longer a difference between dry-run and real build
    required: false
    default: false
runs:
  using: composite
  steps:
    - shell: bash
      run: python3 setup.py bdist_wheel sdist
