name: Sanitise workflow inputs
description: Sets the env vars VERSION and BASE_REF. Should be first step of workflow.
# github.event inputs:
  # version: The version number of the release
  # branch: The name of the branch against which the release PR should be opened
# env outputs:
  # VERSION: (as above)
  # BASE_REF: (the branch name as above)
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      env:
        VERSION: ${{ github.event.inputs.version }}
        BRANCH: ${{ github.event.inputs.branch }}
      run: node sanitize-inputs.js
