name: Sanitise workflow inputs
description: Sets the env vars VERSION and BASE_REF. Should be first step of workflow.
inputs:
  version:
    description: The version number of the release. If this is not set, will use the workflow_dispatch event version input instead.
    required: false
  branch:
    description: The name of the branch against which the release PR should be opened. If this is not set, will use the workflow_dispatch event branch input instead.
    required: false
# env outputs:
  # VERSION: (as above)
  # BASE_REF: (the branch name as above)
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ github.action_path }}
      env:
        VERSION: ${{ inputs.version || github.event.inputs.version }}
        BRANCH: ${{ inputs.branch || github.event.inputs.branch }}
      run: node sanitize-inputs.js
