name: Style test

on:
  pull_request:

jobs:

  style-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2.3.2

    - name: Install (dev) dependencies
      run: npm install

    - name: Style test
      run: npx eslint .
